### ISSUE TITLE
PaygreenJS Abonnement

### ISSUE THREAD

**Issue by David83300** [PayGreen/paygreen-php#101]
Bonjour,
je suis entrain de faire un système d'abonnement sur Laravel avec PaygreenJS et il faut obligatoirement que la case pour enregistrer ma carte soit cochée.
Comment faire pour la rendre obligatoire svp ?
![Screenshot 2023-01-25 at 12-00-21 kudo](https://user-images.githubusercontent.com/119430514/214546612-a369799b-6060-420a-9ae3-bffc2c180523.png)

**Comment by pielrx** [comment]
Bonjour David,

Vous ne pouvez pas techniquement rendre la case à coché obligatoire mais vous pouvez désactiver votre bouton de paiement si celle-ci n'est pas dans l'état que vous souhaitez.
Vous pouvez écouter l'événement REUSABLE_ALLOWED_CHANGE afin de modifier votre bouton de paiement : https://pgjs.paygreen.fr/latest/documentation/enums/types.EventsType.html#REUSABLE_ALLOWED_CHANGE
Ceci vous permettra de `enable` ou `disable` le bouton de paiement.


Il est aussi possible de vous déléguer la gestion du recueil de consentement via la méthode updateConsent (https://developers.paygreen.fr/docs/installation#3-init).

Pour avoir accès à cette méthode vous devez prendre contact avec notre support client afin que votre application soit auditée et validée.

Bonne journée,
