### ISSUE TITLE
Impossible de mettre à jour les données d'une boutique

### ISSUE THREAD

**Issue by ariouche** [PayGreen/paygreen-php#103]
Bonjour, je ne vois aucune fonction (sur l'api ou dans le sdk V3) permettant de mettre à jour une boutique. Comment fait on pour mettre à jour les données d'une boutique svp ?

Merci

**Comment by guillaumbertin** [comment]
Bonjour,

En effet, la méthode de mise à jour n'est pas encore disponible via le SDK.
Elle le sera prochainement, vous pouvez cependant utiliser l'api pour réaliser cette action: https://developers.paygreen.fr/reference/post_update_shop

Nous laissons cette Pull Request ouverte afin de vous informer quand la méthode sera implémentée.

Cordialement,

Guillaume

**Comment by guillaumbertin** [comment]
Bonjour @ariouche ,

Vous pouvez maintenant utiliser la méthode updateShop du Client V3.
```

$response = $client->updateShop(
    $environment->getShopId(),
    (new \Paygreen\Sdk\Payment\V3\Model\Shop())->setName('Nouveau Nom')
);

$jsonResponse = json_decode($response->getBody()->getContents());
```

Cordialement,

Guillaume
