### ISSUE TITLE
la methode listInstrument retourne une erreur 400

### ISSUE THREAD

**Issue by Pixboh** [PayGreen/paygreen-php#105]
La methode du Sdk  $client->listInstrument($buyer_id); retourne une erreur 400 pourtant je passe bien le bon buyer_id.
L'erreur retournée: 

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>400 Bad Request</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Bad Request</h1>
<h2>Your client has issued a malformed or illegal request.</h2>
<h2></h2>
</body></html>

![Screen Shot 2023-04-26 at 16 31 03](https://user-images.githubusercontent.com/25004412/234642225-8d3cdf19-918e-4655-af6f-3758f6e7f20c.png)

**Comment by guillaumbertin** [comment]
Bonjour,

Merci pour votre signalement, un correctif est en cours.

Paygreen

**Comment by guillaumbertin** [comment]
@Pixboh Un correctif vient d'être livré, vous ne devriez plus rencontrer cette 400.

Paygreen

**Comment by Pixboh** [comment]
Bonjour je l'ai toujours. Je suis sur la sanbox. Shop ID sh_ed0954a8fb374323b70ecf96a41a8727

**Comment by guillaumbertin** [comment]
@Pixboh Avez-vous récupéré la dernière version du SDK (1.3.9) ?

**Comment by Pixboh** [comment]
yes c'est bon merci
