### ISSUE TITLE
Pas de données de carte sur les intruments enregistrés

### ISSUE THREAD

**Issue by Pixboh** [PayGreen/paygreen-php#110]
![image](https://user-images.githubusercontent.com/25004412/235630297-fb54a57d-59af-4ae6-8417-35ff6213c7ab.png)

Seul les info du buyer sont retournés au niveau de l'instruments. Les champs concernant la carte enregistré sont vides

**Comment by guillaumbertin** [comment]
Bonjour @Pixboh,

Pouvez-vous m'indiquer l'environnement sur lequel vous réalisez vos appels ? 
Pouvez-vous également me dire la route que vous utilisez pour récupérer ces informations ?

N'hésitez pas à copier les id que vous utilisez ins_af7... , buy_831...

Paygreen

**Comment by guillaumbertin** [comment]
Bonjour @Pixboh,

Avez-vous toujours un soucis avec la récupération des informations ?

Paygreen
