### ISSUE TITLE
Update Payment Config

### ISSUE THREAD

**Issue by thedigital** [PayGreen/paygreen-php#118]
Bonjour,

Je souhaite pouvoir utiliser la mise a jour de PaymentConfig (https://developers.paygreen.fr/reference/post_update_payment_config) via le SDK mais ce n'est actuellement pas implémenté

Est ce que c'est une implémentation prévue dans la roadmap du SDK ? Si oui, une idée de la date de mise à jour ?
Dois-je forker le SDK et l'implémenter moi-même ? Puis-je en faire une pull request ?

Merci d'avance

Guillaume

**Comment by guillaumbertin** [comment]
Bonjour @thedigital ,

Cette fonctionnalité n'a en effet pas été implémentée et n'est pas prévue pour le moment.
Vous pouvez proposer une pull  request.

Guillaume

**Comment by guillaumbertin** [comment]
Bonjour @thedigital,

Un développement est en cours.
Nous mettrons à jour le SDK dans la semaine.

Guillaume

**Comment by thedigital** [comment]
Bonjour @guillaumbertin 
Merci pour l'info, j'ai effectivement vu que c'etait dans les PR en attente.
Avez-vous une visibilité sur la date de mise a dispo officielle ?

**Comment by guillaumbertin** [comment]
Bonjour @thedigital,

La version 1.3.15 vient d'être publiée.

Guillaume

**Comment by thedigital** [comment]
Merci beaucoup @guillaumbertin 

Je viens d'utiliser le nouveau endpoint pour la maj de paymentConfig de la version 1.3.15 et je confirme que c'est fonctionnel et que c'est exactement ce dont nous avions besoin.
C'est parfait, merci !
