### ISSUE TITLE
Implémentation SDK API V3

### ISSUE THREAD

**Issue by makeitje** [PayGreen/paygreen-php#122]
Bonjour, j'ai été redirigé ici par votre service client.

Nous tentons d'implémenter votre SDK PHP pour la plateforme d'un client. Les exemples fournis dans la section suivante ne marche pas.

https://developers.paygreen.fr/docs/payment#create-a-payment-order

La documentation ne précise rien sur les paramètres obligatoires ou non. Je vous joins une capture d'écran de l’appel. J’ai ajouté la méthode setPlatforms(), obligatoire également et qui n’apparait pas dans la documentation. Nous avions déjà ce genre de problèmes en implémentant la V1 et avions un contact direct au sein de votre équipe technique. Est-ce encore possible d’avoir quelqu’un avec qui échanger par mail à ce sujet ?

Je souhaite également tester le paiement via AMEX, existe t’il des contrats fictifs que je peux configurer sur mon espace ?

Dans la capture d'écran, la propriété $_paygreen est une instance de Paygreen\Sdk\Payment\V3\Client;, crée comme suit:

```
$guzzle = new \GuzzleHttp\Client();
$this->_paygreen = new Client($guzzle, new Environment($this->getShopId(), $this->getPrivateKey(), $this->getEnv()));
$response = $this->_paygreen->authenticate();
$data = json_decode($response->getBody()->getContents())->data;
$this->_paygreen->setBearer($data->token);
 
```

le retour de l’appel à la méthode createPaymentOrder:
message => ‘Invalid payment configuration'. Pour tenter d’y remédier, nous avons ajouté l’extrait suivant au début de la méthode:

```
        $paymentConfig = new \Paygreen\Sdk\Payment\V3\Model\PaymentConfig();
        $paymentConfig->setPlatform('bank_card');
//        $paymentConfig->setSellingContractId('sc_0000');
        $paymentConfig->setCurrency('eur');
        $paymentConfig->setConfig(array('config1', 'config2')); // Optional

        $this->_paygreen->createPaymentConfig($paymentConfig, $this->getShopId());
```
![image](https://github.com/PayGreen/paygreen-php/assets/149183912/0c91ce73-a50b-44f1-b322-a3431f6e480b)

**Comment by guillaumbertin** [comment]
Bonjour,

Demande géré par le canal support.
