### ISSUE TITLE
Adresse requise pour créer un Buyer

### ISSUE THREAD

**Issue by sebj54** [PayGreen/paygreen-php#123]
Bonjour,

Dans la doc de l'API, l'adresse n'est pas requise pour créer un Buyer : https://developers.paygreen.fr/reference/post_create_buyer

![image](https://github.com/PayGreen/paygreen-php/assets/5880435/90c6fc1c-7189-43e2-8abf-94fc69cb8cc0)

Par contre, le code `BuyerRequest` ne correspond pas et une exception est levée quand on tente de créer un Buyer sans adresse : 

```
Error: Uncaught Error: Call to a member function getStreetLineOne() on null in /Users/sebjean/projects/payzily.com/vendor/paygreen/paygreen-php/lib/PaygreenSdk/Payment/V3/Request/Buyer/BuyerRequest.php:65
```

Dans le code `billing_address` est toujours présent et un appel (notamment) à `$buyer->getBillingAddress()->getStreetLineOne()` est fait, ce qui cause l'exception

https://github.com/PayGreen/paygreen-php/blob/cea9ab062f2a690ffda39bd77c2fd9ca52fe167d/lib/PaygreenSdk/Payment/V3/Request/Buyer/BuyerRequest.php#L51-L78

**Comment by MaximeLemolt** [comment]
Bonjour @sebj54 , merci pour cette remontée.
Nous avons corrigé cela, nous vous invitions à mettre à jour pour bénéficier du correctif.
Nous n'avons pas utilisé votre fork bien qu'il fut correct car nous avons ajouté une factorisation supplémentaire entre l'update et le create buyer.

Maxime
