### ISSUE TITLE
Problème paiement

### ISSUE THREAD

**Issue by intellagence** [PayGreen/paygreen-php#62]
Bonjour,

J'ai quelques incompréhensions à l'étape de vérification de la key payment order 
![paygreen-create1](https://user-images.githubusercontent.com/83727545/193263838-1a7cdd39-5695-4034-9a95-f53cd78cbdd6.png)

 je créé le buyer et le payment order que j'envoie au développeur front 

![paygreenjs1](https://user-images.githubusercontent.com/83727545/193263494-89c67526-1a7a-432a-8bae-c419b4cfcc2b.png)

le développeur front me retourne l'id de payment order + la public key

![paygreen-confirmation](https://user-images.githubusercontent.com/83727545/193263325-36b6b901-7751-4626-9b3b-00cda56c286a.png)

C'est sur cette route que je rencontre des difficultés, je récupère bien l'id du payment order ainsi que la public key..

mais je n'arrive pas à checker si le paiement est accepté sur paygreen :

![resultat+erreur2](https://user-images.githubusercontent.com/83727545/193263726-3da71fef-6260-43d5-af42-85ed09be46ca.png)

Pourriez-vous m'expliquer ce qui ne va pas,
sur la dernière route, j'ai besoin de vérifier l'état du paiment avec l'id du payment order 

je reste à votre disposition

merci

**Comment by pielrx** [comment]
Bonjour @intellagence,

Tu peux utiliser la méthode getPaymentOrder du client pour récupérer ton PaymentOrder et contrôler son statut.

https://github.com/PayGreen/paygreen-php/blob/master/lib/PaygreenSdk/Payment/V3/Client.php#L225

**Comment by intellagence** [comment]
![resultat](https://user-images.githubusercontent.com/83727545/194444179-7ca46a3a-b4a6-468c-99b4-233ceed52765.png)

Bonjour,

J'ai essayé la méthode getPaymentOrder avec pour argument l'id du payment order mais j'ai l'erreur 401, il manque la public key, que j'ai mais où la placer ?

**Comment by pielrx** [comment]
Bonjour, 

Tu dois t'authentifier pour récupérer un token avant d'effectuer le getPaymentOrder.

Pour info, le token est valable 10 minutes. Il est recommandé de le mettre en cache pour optimiser les performances.

$response = $client->authenticate();
$data = json_decode($response->getBody()->getContents())->data;
$client->setBearer($data->token);

**Comment by intellagence** [comment]
Super merci, c'est fonctionnel ça me retourne bien
```
-reasonPhrase: "OK"
  -statusCode: 200
  -headers: array:12 [▶]
  -headerNames: array:12 [▶]
  -protocol: "1.1"
  -stream: [GuzzleHttp\Psr7\Stream](https://localhost:8000/_profiler/open?file=vendor\guzzlehttp\psr7\src\Stream.php&line=12#line12) {#1554 ▶}
```

J'aurais une dernière questions, dans ma bdd, dans la table commande, qu'ai-je besoin de conserver comme données de paygreen ? le paiement order par exemple ?

**Comment by pielrx** [comment]
@intellagence c'est bien de stocker l'id du paimentOrder en tant qu'identifiant PayGreen dans ta base de données.
