### ISSUE TITLE
Some features seems to be missed in V3

### ISSUE THREAD

**Issue by olvinfoway** [PayGreen/paygreen-php#66]
I use new V3 php SDK for paygreen integration.

I don't see the method to set marketplace fees in PaymentOrder class.
The listTransaction and listBuyers methods of Paygreen Client class always return null while direct requests from guzzle return proper responses.

**Comment by RomainPayGreen** [comment]
Hi there,

I will investigate to understand how to set marketplace fees and why the listTransaction adn listBuyers are not working properly.

Thanks for your feedbacks, I keep you informed.

**Comment by RomainPayGreen** [comment]
Hi @olvinfoway,

We'll add the fees parameter when you create a payment order in the next release.

I didn't find ant problem about the listTransaction and listBuyers, I used this to see the result : 

```
$response = $client->listTransaction();
$data = json_decode($response->getBody()->getContents())->data;
dump($data);

$response = $client->listBuyer();
$data = json_decode($response->getBody()->getContents())->data;
dump($data);
```

How did you setup your request?

Have a good day!
