### ISSUE TITLE
Lien conecs

### ISSUE THREAD

**Issue by Marhime** [PayGreen/paygreen-php#69]
Bonjour,

J'arrive bien à rediriger vers les services swile et restoflash. Par contre conecs, rien ne se passe, la page ne s'ouvre jamais. (Waiting sb-paygreen...)

**Comment by RomainPayGreen** [comment]
Bonjour,

Avez vous déjà réussi a afficher les hosted fields pour le paiement par carte bancaire avec PaygreenJS ? 
https://developers.paygreen.fr/docs/quickstart

Un exemple complet est disponible ici : https://developers.paygreen.fr/recipes/pgjs-conecs-bank-card-payment

C'est le même procédé à effectuer pour intégrer Conecs.

Bonne journée.

**Comment by Marhime** [comment]
Hello,

Yes dans mon code j'arrive bien à renvoyer vers swile ou restoflash comme ceci:

<img width="929" alt="image" src="https://user-images.githubusercontent.com/35594487/203639343-6c40445b-e6c8-47f1-9238-478c141418e2.png">

Mais pour conecs cela ne fonctionne pas...

Ca charge puis plus rien (voir ci dessous)

<img width="526" alt="image" src="https://user-images.githubusercontent.com/35594487/203661581-1f4dd00c-c6b8-486f-8f6c-6611429ed964.png">

**Comment by enzobillisPG** [comment]
Bonjour,

Les moyens de paiement Restoflash et Swile fonctionnent par le biais d'un OAuth (page de connexion sur le site du service). Le moyen de paiemen Conecs lui fonctionne comme une carte bancaire classique. C'est à dire que les champs Numéro de carte, CVV et date d'expiration seront affichés.

Je rebondis sur la question de mon collègue, avez vous intégré le paiement par carte bancaire ? Si oui, vous pouvez utiliser le même composant pour Conecs en précisant simplement "conecs" dans setPaymentMethod.

Sinon, je vous invite à reproduire l'exemple de la documentation: https://developers.paygreen.fr/docs/installation#2-place-the-skeleton où il est précisé que le skeleton contenant les divs paygreen-pan-frame, paygreen-cvv-frame et paygreen-exp-frame doivent être disponible dans votre DOM au moment de l'initialisation de PGJS.

Enfin, voici un exemple d'intégration complet carte bancaire et conecs: https://developers.paygreen.fr/docs/meal-vouchers-bank-card

Je reste à votre disposition si vous avez d'autres questions.
Bonne journée,
Enzo BILLIS

**Comment by Marhime** [comment]
Hello,

Ok j'étais déjà donc mal parti.

Oui j'ai déjà mis en place pour bank_card.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/35594487/204059625-462c4d8a-4865-4056-a790-c6598e552ece.png">

Mais du coup mon design ressemble à ca est-il possible de le réaliser ? (Bank card, et Conecs à deux endroits differents)

<img width="606" alt="image" src="https://user-images.githubusercontent.com/35594487/204062145-4dd1001e-9e47-4e0a-b312-722789e7b7e8.png">

Comment puis-je savoir si PaygreenJS est mount ?

J'utilise React n'auriez vous pas des recommandations ?

**Comment by enzobillisPG** [comment]
Bonjour @Marhime,
Oui vous pouvez tout à fait afficher le formulaire bank_card et conecs suite à deux actions différentes de l'utilisateur (une en cliquant sur le bouton Carte Bancaire et l'autre en clickant sur le bouton Titres Restaurant). Vous devez simplement utiliser la méthode setPaymentConfig("conecs") ou setPaymentConfig("bank_card") appropriée lors du clique.

Pour savoir si PGJS est monté vous pouvez utiliser la méthode paygreenjs.status(), elle est contient des informations qui seront disponible qu'une fois montée (comme le payment order si vous êtes en mode paiement ou simplement les flows). Je vous invite à utiliser un state interne (style pgjsMounted = false) dans votre composant pour garder cela en mémoire. Vous pouvez aussi vous baser sur le tout premier event PAYMENT_FLOW_ONCHANGE qui implicitement indique que PGJS est prêt à fonctionner.

Concernant React, PGJS est développé avec Preact (une version minifié de React) même si l'API de PGJS s'apparente à celle d'une lib JS classique et non d'un wrapper React, la logique interne en hérite (cycle de vie React etc...). Vous pouvez donc être rassuré quant à sa fiabilité. Je vous recommande donc d'intégrer PGJS dans une optique composant propre à React et tout devrait bien se passer.

En espérant avoir répondu à vos questions,
Bonne journée.
Enzo BILLIS

**Comment by enzobillisPG** [comment]
Close due to inactivity
