### ISSUE TITLE
Integration Paygreen on Laravel

### ISSUE THREAD

**Issue by David83300** [PayGreen/paygreen-php#71]
I'm trying to integrate Paygreen with Laravel, but when I do a payment test I get the Shopid at null

This is my code on Controller

```
// USER

$user=auth()->user();
$attributes=$user->getAttributes();
$firstname=$attributes['name'];
$lastname=$attributes['lastname'];
$email=$attributes['email'];
$phone=$attributes['phone'];
$city=$attributes['city'];
$address=$attributes['address'];
$country=$attributes['country'];
$postal=$attributes['postal'];
```

       // AUTH
       $client = new \GuzzleHttp\Client();

       $response = $client->request('POST', 'https://sb-api.paygreen.fr/auth/authentication/'.env('PAYGREEN_SHOP_ID').'/secret-key', [
         'headers' => [
           'Authorization' => env('PAYGREEN_SECRET_KEY'),
         ],
       ]);
       $recup=json_decode($response->getBody()->getContents());
       $token=$recup->data->token;

       // Post Shop ID

       $environment = new \Paygreen\Sdk\Payment\V3\Environment(
           env('PAYGREEN_SHOP_ID'), // Look like this: sh_00000000000000
           env('PAYGREEN_SECRET_KEY'), // Look like this: sk_00000000000000
           env('PAYGREEN_MODE') // Possible values : PRODUCTION, SANDBOX
       );

       $client_paygreen = new \Paygreen\Sdk\Payment\V3\Client($client, $environment);

```
// CREATE PAYMENT ORDER


$object_secret = $client->request('POST', 'https://sb-api.paygreen.fr/payment/payment-orders', [
  'body' => '{"auto_capture":true,"buyer":{"first_name":"'.$firstname.'","last_name":"'.$lastname.'","email":"'.$email.'","phone_number":"'.$phone.'"},"currency":"eur","merchant_initiated":false,"mode":"instant","partial_allowed":false,"shipping_address":{"city":"'.$city.'","country":"'.$country.'","line1":"'.$address.'","postal_code":"'.$postal.'"},"amount":'.$amount.'}',
  'headers' => [
    'accept' => 'application/json',
    'authorization' => 'Bearer '.$token,
    'content-type' => 'application/json',
  ],
]);
$recup=json_decode($object_secret->getBody()->getContents());
$payment_order_id=$recup->data->id;
$object_secret_id=$recup->data->object_secret;

return view('account.payments.paygreen_auth')->with([
    'objectSecret' => $object_secret_id,
    'payment_order_id' => $payment_order_id,
    'amount' => $amount,
]);
```

And my code on View

```
const handlePay = () => {
paygreenjs.submitPayment();
};

const initPGJS = () => {
paygreenjs.attachEventListener(paygreenjs.Events.PAN_FIELD_FULFILLED, () => {
  console.log('pan fullfilled');
  paygreenjs.focus('cvv');
});

paygreenjs.attachEventListener(paygreenjs.Events.CVV_FIELD_FULFILLED, () => {
  paygreenjs.focus('exp');
});


paygreenjs.init({
  paymentOrderID: '<?=$payment_order_id ?>',
  objectSecret: '<?=$objectSecret ?>',
  mode: 'payment',
  modeOptions: {
    authorizedInstrument: false,
  },
  style,
  paymentMethod: 'bank_card',
  publicKey: '<?=env('PAYGREEN_PUBLIC_KEY') ?>',
});
};

window.addEventListener('load', function() {
initPGJS();
});
```

This is my resultat with error 400

`{"type":"bank_card","pan":"4242424242424242","cvv":"123","expirationDate":"1224","reuseAllowed":true,"shopId":null}`

**Comment by enzobillisPG** [comment]
Hi David,

First, could you confirm that you have configured your payment config "bank_card" with the appropriate API route and it's status is validated ? 

Then, do you use a selling distand contract or not ? The test card beginning with 4242 is only for bank_card without distant selling contract. You can refer to this documentation to use the appropriate card: https://developers.paygreen.fr/docs/test-cards

PS: the modeOptions.authorizedInstrument is useless in payment mode, it's only used in instument mode.

Enzo

**Comment by David83300** [comment]
For the distance selling contract I don't know anything, I'm just the developer who has to integrate Paygreen

And yes I confirm that I have set up "bank_card" and the status is validated

**Comment by enzobillisPG** [comment]
You can check the is_vad property by getting your payment config with this route https://developers.paygreen.fr/reference/get_list_payment_configs

**Comment by David83300** [comment]
you are reason 

`"id": "pc_6f6f10659cdc4c99b30f41d92ea8c59d",
      "object": "payment_config",
      "shop_id": "sh_58961a0285584a9487c303e5a8fea38f",
      "platform": "bank_card",
      "status": "payment_config.validated",
      "currency": "eur",
      "selling_contract": {
        "object": "selling_contract",
        "id": "sc_967c6d1fb13342688013f238e62c25ca",
        "number": "1234566",
        "mcc": 4555,
        "max_amount": 15000,
        "status": "selling_contract.created",
        "type": "vads"
      },`
      
      is it normal if the request for "paygreenjs.submitPayment()" sends a "shopid" to null ? or not

**Comment by David83300** [comment]
And another question, I've never done Laravel before.
With paygreenJS how to display visually the result of the request? to say that the payment is confirmed or refused

**Comment by enzobillisPG** [comment]
Hi David,

You have a selling contract into your payment config, so you are using a distant selling contract (contrat de vente à distance in French). Please use the test Bank Card (VAD) https://developers.paygreen.fr/docs/test-cards#bank-card-vad instead of the first you used.

Yes it's normal if paygreenjs send shopid null, don't worry.

PGJS is a front-end library, which mean it must be integrated in the front part of your application. I'm not a Laravel expert but the front part of this Framework seems to be done with Blade. So you must add the .init() function and all the listeners into a Blade template.
You can refers to those examples: https://developers.paygreen.fr/docs/meal-vouchers-bank-card
To handle a confirmed or refused payment you can do it with the .addEventListener() PGJS function and with the webhooks offered by the Paygreen API (https://developers.paygreen.fr/docs/listeners)

Enzo

**Comment by David83300** [comment]
Thank you very much. If I understand correctly I use the JS function depending on whether it is  FAIL or DONE to redirect to a Blade and display the result.

**Comment by enzobillisPG** [comment]
Indeed, it's should work.
