### ISSUE TITLE
Status PaygreenJS

### ISSUE THREAD

**Issue by David83300** [PayGreen/paygreen-php#73]
Bonjour,
j'ai reussi à integrer Paygreen dans Laravel mais j'aimerai  traiter les statuts différents de 200 (comme essayer une carte en SVAD alors que le contrat n'autorise que le VAD => erreur 400)
Savez-vous comment faire ?

**Comment by pielrx** [comment]
Bonjour David,

Le type de carte à utilisé dépend du type de payment_config que tu utilises. Les cartes SVAD fonctionnent avec un payment_config SVAD et les cartes VAD fonctionnent avec un payment_config VAD.

Voici les différentes cartes à disposition pour simuler les différents types de retour : https://developers.paygreen.fr/docs/test-cards

**Comment by David83300** [comment]
Cela n'etait pas ma question. j'ai du mal formuler désolé
Ce que je voulais savoir c'est si je reçois un status autre que 200/204 de la requete initial
comment je peux ecouter avec paygreenjs le status pour executer un code en retour ?
car si j'ai un contrat en VAD et qu'un client essai avec une SVAD, il faut bien que cela reagisse à l'erreur 400 que ça genere

**Comment by David83300** [comment]
comme par exemple
```
paygreenjs.attachEventListener(
    paygreenjs.Events.PAYMENT_FAIL,
    (event) => {
        window.location="{{ route('paygreen.traitement', ['payment_order_id' =>$payment_order_id ]) }}";
    },
);
```

mais pour un status de la requete initial svp

**Comment by enzobillisPG** [comment]
Bonjour David,

La gestion des erreurs ou des transaction refusée se fait avec la fonction paygreenjs.attachEventListener. Dans l'exemple que vous fournissez, vous gérez une redirection dès qu'un PAYMENT_FAIL est levé. 
Vous pouvez aussi écouter les événements ERROR (pour les erreurs internes à PGJS) et TOKEN_FAIL (pour les erreurs liées à une mauvaise carte par exemple). 

Dès lorsqu'un de ces événements est levé, vous pouvez lire le event.detail qui contient très souvent l'origine de l'erreur (nous travaillons actuellement à ce que le contenu de event.detail soit plus détaillé).
Si vous souhaitez plus de détail sur l'erreur après tokenization (par exemple 3ds échoué etc...) vous pouvez vous référer au payment-order qui contient le détail. Pour ce faire deux possibilité:
- Vous rediriger vos utilisateurs vers une page /erreur par exemple, durant laquelle vous récupérer le payment-order auprès de l'api et vous adaptez l'affichage en fonction du code erreur
- Vous restez sur la même page où PGJS est initialisé et vous utilisez la fonction paygreenjs.status() afin de récupérer une copie du payment-order mis à jour. Vous pourrez ensuite réagir en fonction des erreurs contenues dedans.

En espérant avoir pu vous aider.
Enzo

**Comment by enzobillisPG** [comment]
Close due to inactivity
