### ISSUE TITLE
Systeme d'abonnement Laravel avec Paygreen

### ISSUE THREAD

**Issue by David83300** [PayGreen/paygreen-php#96]
Bonjour, pourriez-vous me dire comment je créé un systeme d'abonnement svp ?
De ce que l'on m'a dit c'est de faire un CRON et de recreer des paiements à date réguliere.
Je dois récuperer l'id de l'operation ? de la transaction ? pour effectuer ce nouveau paiement.
et surtout comment le faire via PHP, vu que le paiement initial est fait avec PaygreenJS svp.

Et aussi quels sont les élements que j'ai besoin de récuperer du paiement initial ? 
il doit etre en mode instrument ?
Cordialement

**Comment by guillaumbertin** [comment]
Bonjour,

Vous ne pouvez pas créer d'abonnement directement avec notre solution.
Vous devez gérer la partie "échéancier" via votre système d'information.

1 étape: Autoriser un instrument grâce à un premier paiement, stocker cet instrument dans votre SI.
2 étape: Pour chaque échéance suivante, utiliser cet instrument en créant un nouveau PaymentOrder: https://developers.paygreen.fr/reference/post_create_payment_order (paramètre: instrument)

Cordialement,
Guillaume - Paygreen

**Comment by David83300** [comment]
Merci pour votre réponse,
du coup je récupère l'instrument ID que je stock en base de donnée, et rien d'autre  ?
l'amount etc sera refait automatiquement ?

**Comment by guillaumbertin** [comment]
@David83300 ,

Dans votre système vous devez gérer un échéancier, par exemple pour un abonnement de 10€ pendant 3 mois, vous allez avoir:
1ere echéance : 10€ - 24.01.2023
2ieme échéance : 10€ - 24.02.2023
3ieme échéance : 10€ - 24.03.2023

Un cron permettra ensuite de vérifier qu'une échéance doit être émise, si c'est le cas, vous devez créer un nouveau PaymentOrder avec le montant de l'échéance et l'instrument.

Vous avez deux possibilités pour récupérer l'instrument.
- le stocker en base et le réutiliser quand vous souhaitez
- lister les instruments du buyer concerné et récupérer l'instrument que vous souhaitez utiliser (https://developers.paygreen.fr/reference/get_list_instruments)


Cordialement,
Guillaume - Paygreen

**Comment by David83300** [comment]
Merci de vos précisions :)
