### ISSUE TITLE
Pagination shop list request

### ISSUE THREAD

**Issue by pielrx** [PayGreen/paygreen-php#99]
En utilisant le SDK pour PHP la listing des Shops ne retourne que les 20 premiers Shops dans le code du SDK [paygreen-php/ShopRequest.php at master · PayGreen/paygreen-php](https://github.com/PayGreen/paygreen-php/blob/master/lib/PaygreenSdk/Payment/V3/Request/Shop/ShopRequest.php) l’appel à l’API (public function getListRequest()) ne permet pas de spécifier une numero de page ou une limite

**Comment by guillaumbertin** [comment]
Disponible depuis la release 1.3.8
